<a href="https://colab.research.google.com/github/pnp642001/Data-Science-Masters-Bootcamp/blob/main/February_26_2023_Assignment.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Consider the below code to answer further questions:

import numpy as np

list_ = [ ‘1’ , ’2’ , ‘3’ , ‘4’ , ‘5’ ]

array_list = np.array(object = list_)

In [1]:

import numpy as np
list_ = [ '1','2','3','4','5' ]
array_list = np.array(object = list_)

Q1. Is there any difference in the data type of variables list_ and array_list? If there is then write a code
to print the data types of both the variables.<br>
ANS:<br>
The data type of list_ and array_list can be different depending on how array_list is defined. If array_list is defined using the array module in Python, then its data type will be array.array, which is a specialized data type for storing homogeneous data. On the other hand, list_ is a built-in data type in Python for storing heterogeneous data.

In [2]:
import array

# Define a list and an array
list_ = [1, 'hello', True]
array_list = array.array('i', [1, 2, 3])

# Print the data types of both variables
print("Data type of list_:", type(list_))
print("Data type of array_list:", type(array_list))

Data type of list_: <class 'list'>
Data type of array_list: <class 'array.array'>


Q2. Write a code to print the data type of each and every element of both the variables list_ and
arra_list.

In [3]:
# Print the data type of each element in list_
print("Data type of each element in list_:")
for element in list_:
    print(type(element))

# Print the data type of each element in array_list
print("Data type of each element in array_list:")
for element in array_list:
    print(type(element))

Data type of each element in list_:
<class 'int'>
<class 'str'>
<class 'bool'>
Data type of each element in array_list:
<class 'int'>
<class 'int'>
<class 'int'>


Q3. Considering the following changes in the variable, array_list:

array_list = np.array(object = list_, dtype = int)

Will there be any difference in the data type of the elements present in both the variables, list_ andarra_list? If so then print the data types of each and every element present in both the variables, list_ and arra_list.

ANS:

Yes, there will be a difference in the data types of the elements present in list_ and array_list 

In [4]:
import numpy as np
list_ = [ '1','2','3','4','5' ]
array_list = np.array(object = list_)

In [5]:
array_list = np.array(object = list_, dtype = int)

In [6]:
print("Data type of each element in list_:")
for element in list_:
    print(type(element))

# Print the data type of each element in array_list
print("Data type of each element in array_list:")
for element in array_list:
    print(type(element))

Data type of each element in list_:
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
Data type of each element in array_list:
<class 'numpy.int64'>
<class 'numpy.int64'>
<class 'numpy.int64'>
<class 'numpy.int64'>
<class 'numpy.int64'>


Consider the below code to answer further questions:

import numpy as np

num_list = [ [ 1 , 2 , 3 ] , [ 4 , 5 , 6 ] ]

num_array = np.array(object = num_list)

Q4. Write a code to find the following characteristics of variable, num_array:

(i) shape

(ii) size

In [7]:
import numpy as np
num_list = [ [ 1 , 2 , 3 ] , [ 4 , 5 , 6 ] ]
num_array = np.array(object = num_list)

In [8]:
num_array.shape

(2, 3)

In [9]:
num_array.size

6

Q5. Write a code to create numpy array of 3*3 matrix containing zeros only using a numpy array

creation function.

[Hint: The size of the array will be 9 and the shape will be (3,3).]

In [11]:
array_5=np.zeros((3,3))
print(array_5)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


Q6. Create an identity matrix of shape (5,5) using numpy functions?
[Hint: An identity matrix is a matrix containing 1 diagonally and other elements will be 0.]

In [12]:
array_6=np.eye(5)
print(array_6)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]
